# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ExampleApp
  pod 'LinkedinSwift', '~> 1.6.6'

  target 'ExampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
